# Generated by Django 2.2.6 on 2020-02-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quadrant',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
