# Generated by Django 2.2.6 on 2020-04-11 18:23

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_degree_experience_intention_interest_logistic_profcourse_profskill_techcourse_techskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quadrant',
        ),
        migrations.RemoveField(
            model_name='project',
            name='secondary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technical',
        ),
        migrations.AddField(
            model_name='project',
            name='cohort',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contact_first_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contact_last_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(default='none', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='degree',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='experience',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_address',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='organization_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='organization_website',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='other_skills',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='prof_courses',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='prof_skills',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='project_categories',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(default='none', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech_courses',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_skills',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='project',
            name='time_commitment',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='unique_id',
            field=models.CharField(default=datetime.datetime.now(), max_length=300),
            preserve_default=False,
        ),
    ]
