# Generated by Django 2.2.6 on 2020-04-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200411_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logistics',
        ),
        migrations.AddField(
            model_name='project',
            name='flexible_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='work_remotely',
            field=models.BooleanField(default=False),
        ),
    ]
