# Generated by Django 2.2.6 on 2020-04-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200411_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fin_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='international',
            field=models.BooleanField(default=False),
        ),
    ]
