# Generated by Django 2.2.6 on 2020-04-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20200411_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fin_aid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='international',
        ),
    ]
