# Generated by Django 2.2.6 on 2019-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_id', models.CharField(max_length=100)),
                ('quadrant', models.CharField(max_length=100)),
                ('technical', models.DecimalField(decimal_places=3, max_digits=5)),
                ('professional', models.DecimalField(decimal_places=3, max_digits=5)),
                ('availability_duration', models.CharField(max_length=100)),
                ('availability_time', models.CharField(max_length=100)),
                ('work_factors', models.CharField(max_length=100)),
                ('interest_buckets', models.CharField(max_length=100)),
                ('other', models.TextField(max_length=500)),
            ],
        ),
    ]
