# Generated by Django 2.2.6 on 2020-04-10 00:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='quadrant',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='resume_id',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='other',
            new_name='other_skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='availability_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interest_buckets',
        ),
        migrations.RemoveField(
            model_name='student',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='student',
            name='technical',
        ),
        migrations.RemoveField(
            model_name='student',
            name='work_factors',
        ),
        migrations.AddField(
            model_name='student',
            name='eid',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default='none', size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='intentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='linkedIn',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='logistics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='prof_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='prof_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='resume_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='tech_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tech_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['none'], size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='time_commitment',
            field=models.CharField(default=['none'], max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
