# Generated by Django 2.2.6 on 2020-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
