# Generated by Django 2.2.6 on 2020-04-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='logistics',
        ),
        # migrations.AddField(
        #     model_name='student',
        #     name='transportation',
        #     field=models.BooleanField(),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='flexible_hours',
        #     field=models.BooleanField(),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='work_remotely',
        #     field=models.BooleanField(),
        # ),
    ]
