# Generated by Django 2.2.6 on 2020-04-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='flexible_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='work_remotely',
            field=models.BooleanField(default=False),
        ),
    ]
