# Generated by Django 2.2.6 on 2020-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200411_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fin_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='international',
            field=models.BooleanField(default=False),
        ),
    ]
