# Generated by Django 2.2.6 on 2020-04-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='student_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
