# Generated by Django 2.2.6 on 2020-12-28 19:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20201228_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=djongo.models.fields.DictField(default={}),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=djongo.models.fields.DictField(default={}),
        ),
    ]
