# Generated by Django 2.2.6 on 2020-04-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='organization_form_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='student_form_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
